### ISSUE TITLE
Invalid Taxi node slot LUA error

### ISSUE THREAD

**Issue by dblanch369** [ramblin-rose/wow-FlightMaster#7]
Getting this error.  I assume it was the most recent phase content patch that is causing it. No clue what is causing it. :(. The result is that one can no longer zoom in and out as the add-on intends.

13x ...aceFlightMaster/FlightMasterDataProvider.lua:152: Invalid taxi node slot
[string "=[C]"]: in function `TaxiNodeCost'
[string "@FlightMaster/FlightMasterDataProvider.lua"]:152: in function <...aceFlightMaster/FlightMasterDataProvider.lua:140>

Locals:
(*temporary) = 40

**Comment by ramblin-rose** [comment]
Thanks for posting the error, I will try to reproduce.

**Comment by ramblin-rose** [comment]
@dblanch369, Regretably I am unable to reproduce the error.  For example, zooming into a Hyjal flight path (below) produced no LUA errors.

If you would be kind enough to provide the steps necessary to reproduce the issue it would be most appreciated, e.g. is there a node for an unknown flight path in a zone, is this a specific zone, etc. Otherwise let me know if I have misunderstood you, and of course I ask you verify you have the latest version installed.

<img width="859" alt="image" src="https://github.com/user-attachments/assets/092a87ae-afe6-4e50-9a71-d255f93de7cb">

**Comment by ramblin-rose** [comment]
#8 does not answer the issue as to why the node's index of out of bounds, but does guard against an invalid taxi node slot.

@dblanch369 thanks for the report.
